FROM python:3.11-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apk add --no-cache gcc python3-dev musl-dev linux-headers && \
    pip install flask psutil && \
    apk del gcc python3-dev musl-dev linux-headers

CMD ["python", "app.py", "--config", "data/config.json"]
