import os
import json
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

DEFAULT_RULES = {
    "ip_blocklist.json": [
        "192.168.1.0"
    ],
    "headers_patterns.json": [
        r"(?i)union\s+select",
        r"(?i)or\s+1=1",
        r"(?i)drop\s+table",
        r"(?i)insert\s+into",
        r"(?i)delete\s+from",
        r"(?i)update\s+.*\s+set",
        r"(?i)exec\s*\(",
        r"(?i)execute\s*\(",
        r"(?i)script\s*>",
        r"(?i)javascript:",
        r"(?i)onerror\s*=",
        r"(?i)onload\s*=",
        r"<\?php",
        r"<%",
        r"base64_decode",
        r"eval\s*\(",
        r"system\s*\(",
        r"passthru\s*\(",
        r"shell_exec",
        r"(?i)wget\s+",
        r"(?i)curl\s+",
        r"\.\./\.\./",
        r"\.\.\\\.\.\\",
        r"/etc/passwd",
        r"/etc/shadow",
        r"c:\\windows",
        r"cmd\.exe",
        r"powershell"
    ],
    "user_agents.json": [
        "sqlmap",
        "nikto",
        "nmap",
        "masscan",
        "zap",
        "burp",
        "fuzz",
        "havij",
        "acunetix",
        "netsparker",
        "appscan",
        "webinspect",
        "metasploit",
        "w3af",
        "dirbuster",
        "gobuster",
        "wfuzz",
        "hydra",
        "medusa",
        "nessus",
        "openvas",
        "skipfish",
        "vega",
        "paros",
        "curl",
        "wget",
        "python-requests",
        "scrapy",
        "phantomjs",
        "headless"
    ],
    "paths.json": [
        r"/wp-admin",
        r"/wp-login\.php",
        r"/wp-content/uploads/.*\.php",
        r"/phpmyadmin",
        r"/pma",
        r"/mysql",
        r"/adminer",
        r"/\.env",
        r"/\.git",
        r"/\.svn",
        r"/\.hg",
        r"/\.DS_Store",
        r"/\.htaccess",
        r"/\.htpasswd",
        r"/config\.php",
        r"/configuration\.php",
        r"/settings\.php",
        r"/\.config",
        r"/backup",
        r"/\.backup",
        r".*\.bak",
        r".*\.old",
        r".*\.tmp",
        r".*\.swp",
        r".*\.sql",
        r".*\.zip",
        r".*\.tar\.gz",
        r".*\.rar",
        r"../etc/passwd",
        r"../../etc/passwd",
        r"../../../etc/passwd",
        r"\.\.\/",
        r"\.\.\\",
        r"/etc/shadow",
        r"/proc/self/environ",
        r"/var/log",
        r"c:\\windows",
        r"c:\\boot\.ini",
        r"<script>",
        r"<script\s",
        r"<\?php",
        r"<%",
        r"eval\(",
        r"(?i)union\s+select",
        r"(?i)or\s+1=1",
        r"(?i)and\s+1=1",
        r"(?i)drop\s+table",
        r"(?i)insert\s+into",
        r"(?i)delete\s+from",
        r"/admin",
        r"/administrator",
        r"/manager",
        r"/console",
        r"/shell",
        r"/webshell",
        r"/backdoor",
        r"/c99",
        r"/r57"
    ],
    "body_patterns.json": [
        r"(?i)union\s+select",
        r"(?i)union\s+all\s+select",
        r"(?i)or\s+1=1",
        r"(?i)or\s+'1'='1",
        r"(?i)or\s+\"1\"=\"1\"",
        r"(?i)and\s+1=1",
        r"(?i)and\s+'1'='1",
        r"(?i)drop\s+table",
        r"(?i)drop\s+database",
        r"(?i)insert\s+into",
        r"(?i)delete\s+from",
        r"(?i)update\s+.*\s+set",
        r"(?i)exec\s*\(",
        r"(?i)execute\s*\(",
        r"(?i)xp_cmdshell",
        r"(?i)sp_executesql",
        r"<script>",
        r"<script\s",
        r"</script>",
        r"javascript:",
        r"onerror\s*=",
        r"onload\s*=",
        r"onclick\s*=",
        r"onmouseover\s*=",
        r"onfocus\s*=",
        r"<iframe",
        r"<embed",
        r"<object",
        r"<\?php",
        r"<%",
        r"base64_decode",
        r"eval\s*\(",
        r"assert\s*\(",
        r"system\s*\(",
        r"passthru\s*\(",
        r"shell_exec",
        r"exec\s*\(",
        r"popen\s*\(",
        r"proc_open",
        r"pcntl_exec",
        r"\$_GET\[",
        r"\$_POST\[",
        r"\$_REQUEST\[",
        r"\$_COOKIE\[",
        r"\$_SERVER\[",
        r"file_get_contents",
        r"file_put_contents",
        r"fopen\s*\(",
        r"readfile\s*\(",
        r"(?i)wget\s+",
        r"(?i)curl\s+",
        r"\.\./\.\./",
        r"\.\.\\\.\.\\",
        r"/etc/passwd",
        r"/etc/shadow",
        r"c:\\windows",
        r"c:\\boot\.ini",
        r"cmd\.exe",
        r"powershell\.exe",
        r"bash\s+-c",
        r"sh\s+-c",
        r"/bin/bash",
        r"/bin/sh",
        r"nc\s+-",
        r"netcat",
        r"telnet",
        r"<!--#exec",
        r"<!--#include"
    ]
}


def initialize_default_rules(rules_dir):
    if not os.path.exists(rules_dir):
        logger.warning(f"Rules directory '{rules_dir}' does not exist. Skipping initialization.")
        return
    
    created_count = 0
    for filename, rules in DEFAULT_RULES.items():
        rule_path = os.path.join(rules_dir, filename)
        if not os.path.exists(rule_path):
            try:
                with open(rule_path, "w", encoding="utf-8") as f:
                    json.dump(rules, f, indent=2)
                logger.info(f"Created default rules file: {filename}")
                created_count += 1
            except Exception as e:
                logger.error(f"Failed to create default rules file {filename}: {e}")
    
    if created_count > 0:
        logger.info(f"Initialized {created_count} default rule files")
    else:
        logger.info("All default rule files already exist")
